# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A logistic regression method using Rcpp
#' @description A logistic regression method using Rcpp
#' @param explain the design matrix 
#' @param response the response vector y
#' @return the estimated coefficients of variables
#' @export
logistic_regression <- function(explain, response) {
    .Call('_StatComp22011_logistic_regression', PACKAGE = 'StatComp22011', explain, response)
}

